---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600

    - name: Make sure git is installed.
      ansible.builtin.apt:
        name: git
        state: present

  roles:
    - role: djonasson.conky
